### ISSUE TITLE
applied to tweets / flauBERT / sentiment discovery

### ISSUE THREAD

**Issue by lucmichalski** [oliverproud/bert-sequence-classification#1]
Hi,

Hope you are all well !

I wanted to test your repository with french tweets. Is there a way to swap models to https://github.com/getalp/Flaubert ?

Ultimate question, how complicated is to re-use https://github.com/NVIDIA/sentiment-discovery to have a wider scope of emotions ?

Thanks in advance for any input or insights.

Cheers,
Luc

**Comment by oliverproud** [comment]
Hi, 

1. You can swap the models easily by using the HuggingFace transformers library by importing FlauBERT [see the link you gave me](https://github.com/getalp/Flaubert#21-using-flaubert-with-hugging-faces-transformers):
`from transformers import FlaubertModel, FlaubertTokenizer` and changing `DISTILBERT_MODEL = [(DistilBertModel, DistilBertTokenizer, 'distilbert-base-cased')]` to `FLAU_BERT_MODEL = [(FlaubertModel, FlaubertTokenizer, 'flaubert-base-uncased')]`. However, you would want to use a french dataset with FlauBERT which would mean tweaking some things in training custom to your problem because it would be a different dataset.

2. I'm not sure I understand what you mean by re-using that repository as it isn't related to HuggingFace's transformers library and looks to be a standalone library that supplies everything necessary to be used. 

Best,
Oliver
